### ISSUE TITLE
设置TRAMP时，出现错误

### ISSUE THREAD

**Issue by alyato** [slegetank/.emacs.d#1]
@slegetank hi, 我用你的TRAMP配置的时候，出现错误。
错误提示

> Symbol's function definition is void: tramp-set-completion-function
 
然后我用c -h f 并没有`tramp-set-completion-function`这个函数。

**Comment by slegetank** [comment]
1 Emacs什么版本？(emacs --version)
2 系统是什么？
3 emacs --debug-init，把错误信息打出来看看。

**Comment by alyato** [comment]
hi，@slegetank 我忘了加`(require tramp)`,现在可以,没有错误了。
我在使用的过程中又出现错误。

> ssh:counld not resolve the hostname `202.122.241.223`:name or service are unknown

.ssh/config中
Host `223`
HostName `202.122.241.223`
User `myName`
在.authinfo中
machine `223` port `ssh` login `myName` password `myPasswd`

**Comment by slegetank** [comment]
在minibuffer里输入双斜杠后输入的是223:而不是ssh:223，你是这样的吗？
![1](https://user-images.githubusercontent.com/4961343/27817955-37278606-60c6-11e7-97d1-1ea644da6c27.gif)

**Comment by alyato** [comment]
没有输入ssh：223
我的第一次输入操作显示：
![1o](https://user-images.githubusercontent.com/6815071/27830830-c0e05768-60fa-11e7-861b-0c4eff1d8f6d.png)
第二次的操作显示：
![2o](https://user-images.githubusercontent.com/6815071/27830861-dd592442-60fa-11e7-8739-69a3b65e413e.png)
回车之后，输出错误：

> ssh:counld not resolve the hostname 202.122.241.223:name or service are unknown

我的设置：
emacs:
![22o](https://user-images.githubusercontent.com/6815071/27830945-3aae09c8-60fb-11e7-8b42-a10dd90b0b58.png)
config设置:
![33o2](https://user-images.githubusercontent.com/6815071/27831052-82f96560-60fb-11e7-82cc-e037864c82c3.png)
.autoinfo设置

> machine 223 port sshx login b3432 password myroot

**Comment by slegetank** [comment]
把你qq号发我邮箱，qq聊吧

**Comment by alyato** [comment]
2073119629

2017-07-05 9:41 GMT+08:00 slegetank <notifications@github.com>:
